### ISSUE TITLE
Trying to export data lead to an Error 500

### ISSUE THREAD

**Issue by Kazer67** [EdwinRodger/MyMangaDataBase#7]
### Steps to reproduce

Installed successfully on a RaspberryPi running DietPi.
Added a test Manga.

Then trying to export and immediately get a Error 500

![image](https://github.com/EdwinRodger/MyMangaDataBase/assets/45577220/1ee83028-8f76-4e7d-a728-bf167e42bb1c)

### Expected behavior

Having the ability to export the data.

### Actual behavior

Trying to export give a Error 500

### MyMangaDataBase version

2.4.0

### Other details

```
dietpi@DietPi:~/MyMangaDataBase-main$ python3 app.py 
Server running on http://0.0.0.0:6070
ERROR:src:Exception on /manga/export [GET]
Traceback (most recent call last):
  File "/home/dietpi/.local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/.local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/.local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/.local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/MyMangaDataBase-main/src/manga/routes.py", line 337, in export
    return send_file(f"MMDB-Manga-Export-{today_date}.zip")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/.local/lib/python3.11/site-packages/flask/helpers.py", line 499, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dietpi/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 427, in send_file
    stat = os.stat(path)
           ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dietpi/MyMangaDataBase-main/src/MMDB-Manga-Export-2024-05-31.zip'
INFO:tdm:[2024-May-31 14:21] 192.168.1.10 GET http /manga/export? 500 INTERNAL SERVER ERROR

```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the lastest version.
- [X] I will fill out all of the requested information in this form.

**Comment by EdwinRodger** [comment]
Fixed it here f9fcf78f66a6067429a56fa793d1c44b064aca97
Tried and tested using WSL. If you have anymore problems after this, let me know.

**Comment by Kazer67** [comment]
Just tested with the fix, I can confirm backup work.

I also tried restore, which work as well.
